HACK: mesa: i830: Fix -Wxor-used-as-pow build error
This one is most likely a false positive because it
looks like "^" operator is indeed used for XOR
operation in the surrounding code context and not as
POW operator.

So just used the result "1" to silence the following
build Werror. I honestly don't know if it is correct.

"
src/mesa/drivers/dri/i915/i830_state.c:605:31: \
    error: result of 'CULLMODE_CW ^ CULLMODE_CCW' is 1; did you mean '1 << CULLMODE_CCW' (8)? [-Werror,-Wxor-used-as-pow]
         mode ^= (CULLMODE_CW ^ CULLMODE_CCW);
                  ~~~~~~~~~~~~^~~~~~~~~~~~~~
                  1 << CULLMODE_CCW
src/mesa/drivers/dri/i915/i830_state.c:605:31: \
    note: replace expression with '0x2 ^ CULLMODE_CCW' to silence this warning
"

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
Change-Id: I43aedc189d8eb2b535d0ed264f3185fdf70144e8